---
- name: update yum
  get_url: 
    url:  http://mirrors.aliyun.com/repo/epel-7.repo
    dest: /etc/yum.repos.d/epel.repo 

- name: update php-fpm source
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
    state: present

- name: install php-fpm
  yum: name={{ item.name }} state=present
  with_items:
    - name: "yum-utils"
    - name: "php72" 
    - name: "php72-php-fpm"
    - name: "php72-php-mysqlnd" 

- name: start php service
  systemd:
    name: php72-php-fpm
    state: started
    enabled: true